/*
 * Copyright (c) 2026 CNCKitchen (Stefan Hermann) and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 */

// Design surfaces for the procedural design generator.
//   uses    the sliders that affect the pattern (the rest are hidden)
//   labels  per-pattern names for generic slots → i18n key design.label.<name>

export const DESIGN_TYPES = [
  // ── Generative / parametric ──
  { id: 'labyrinth', name: 'Coral Labyrinth', tileFrac: 0.35,
    uses: ['density', 'width', 'softness', 'waviness'], labels: { density: 'scale', width: 'ridgeWeight', waviness: 'flow' },
    params: { pattern: 'labyrinth', density: 9, width: 0.5, softness: 0.45, waviness: 0 } },
  { id: 'bloom', name: 'Cellular Bloom', tileFrac: 0.35,
    uses: ['density', 'width', 'softness', 'waviness'], labels: { density: 'scale', width: 'ridgeWeight', waviness: 'flow' },
    params: { pattern: 'bloom', density: 8, width: 0.5, softness: 0.45, waviness: 0 } },
  { id: 'flowLines', name: 'Flow Lines', tileFrac: 0.5,
    uses: ['density', 'angle', 'width', 'softness', 'waviness', 'detail', 'variation'],
    labels: { density: 'lines', waviness: 'flow', detail: 'interlines', variation: 'fade' },
    params: { pattern: 'flowLines', density: 28, angle: 0, width: 0.35, softness: 0.6, waviness: 0.6, detail: 0, variation: 0 } },
  { id: 'gyroid', name: 'Gyroid', tileFrac: 0.7,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'variation', 'asymmetry', 'bubble'], labels: { width: 'wall', waviness: 'morph', accent: 'slice', variation: 'thicknessVar' },
    params: { pattern: 'gyroid', density: 2, width: 0.35, softness: 0.6, waviness: 0.4, accent: 0.25, variation: 0.3, asymmetry: 0.3, bubble: 0 } },
  { id: 'trabecular', name: 'Trabecular Bone', tileFrac: 0.7,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'variation', 'asymmetry', 'bubble'], labels: { width: 'wall', waviness: 'morph', accent: 'slice', variation: 'thicknessVar' },
    params: { pattern: 'trabecular', density: 2, width: 0.3, softness: 0.7, waviness: 0.5, accent: 0.1, variation: 0.6, asymmetry: 0.7, bubble: 0.35 } },
  { id: 'schwarzP', name: 'Schwarz Pores', tileFrac: 0.7,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'variation', 'asymmetry', 'bubble'], labels: { width: 'wall', waviness: 'morph', accent: 'slice', variation: 'thicknessVar' },
    params: { pattern: 'schwarzP', density: 3, width: 0.5, softness: 0.7, waviness: 0.3, accent: 0.5, variation: 0.3, asymmetry: 0.45, bubble: 0.8 } },
  { id: 'schwarzD', name: 'Diamond Lattice', tileFrac: 0.7,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'variation', 'asymmetry', 'bubble'], labels: { width: 'wall', waviness: 'morph', accent: 'slice', variation: 'thicknessVar' },
    params: { pattern: 'schwarzD', density: 2, width: 0.3, softness: 0.6, waviness: 0.3, accent: 0.2, variation: 0.2, asymmetry: 0.25, bubble: 0 } },
  { id: 'neovius', name: 'Neovius', tileFrac: 0.7,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'variation', 'asymmetry', 'bubble'], labels: { width: 'wall', waviness: 'morph', accent: 'slice', variation: 'thicknessVar' },
    params: { pattern: 'neovius', density: 2, width: 0.3, softness: 0.6, waviness: 0.35, accent: 0.4, variation: 0.3, asymmetry: 0.4, bubble: 0.15 } },
  { id: 'voronoiLattice', name: 'Voronoi Lattice', tileFrac: 0.35,
    uses: ['density', 'width', 'softness', 'variation', 'waviness', 'accent', 'detail'],
    labels: { density: 'cells', width: 'strut', variation: 'irregularity', waviness: 'flow', accent: 'fillet', detail: 'cellDomes' },
    params: { pattern: 'voronoiLattice', density: 7, width: 0.35, softness: 0.65, variation: 0.7, waviness: 0.3, accent: 0.5, detail: 0 } },
  { id: 'modRibs', name: 'Kinetic Ribs', tileFrac: 0.5,
    uses: ['density', 'angle', 'softness', 'waviness', 'waveCount', 'accent', 'variation'],
    labels: { density: 'ribs', waviness: 'modulation', waveCount: 'modWaves', accent: 'drift', variation: 'depthMod' },
    params: { pattern: 'modRibs', density: 14, angle: 90, softness: 0.65, waviness: 0.8, waveCount: 2, accent: 0.25, variation: 0.5 } },
  // ── Horology ──
  { id: 'geneva', name: 'Côtes de Genève', tileFrac: 0.3,
    uses: ['density', 'angle', 'accent', 'detail'], labels: { density: 'stripes', accent: 'sweepArcs', detail: 'arcFineness' },
    params: { pattern: 'geneva', density: 5, angle: 0, accent: 0.7, detail: 0.35 } },
  { id: 'clous', name: 'Clous de Paris', tileFrac: 0.2,
    uses: ['density', 'angle', 'width', 'softness', 'accent'], labels: { width: 'pointed', accent: 'grooves' },
    params: { pattern: 'clous', density: 14, angle: 45, width: 0.9, softness: 0.2, accent: 0.6 } },
  { id: 'barleycorn', name: 'Barleycorn Guilloché', tileFrac: 0.3,
    uses: ['density', 'angle', 'width', 'softness', 'waviness', 'waveCount', 'accent'],
    labels: { density: 'lines', width: 'engraving', waviness: 'amplitude', accent: 'interlace' },
    params: { pattern: 'barleycorn', density: 24, angle: 0, width: 0.25, softness: 0.5, waviness: 0.4, waveCount: 6, accent: 0.5 } },
  // ── Japanese / Islamic craft ──
  { id: 'seigaiha', name: 'Seigaiha', tileFrac: 0.3,
    uses: ['density', 'waveCount', 'width', 'softness', 'accent'], labels: { waveCount: 'rings', width: 'line', accent: 'rim' },
    params: { pattern: 'seigaiha', density: 5, waveCount: 4, width: 0.35, softness: 0.6, accent: 0.4 } },
  { id: 'asanoha', name: 'Asanoha Kumiko', tileFrac: 0.35,
    uses: ['density', 'width', 'softness', 'accent'], labels: { width: 'line', accent: 'frame' },
    params: { pattern: 'asanoha', density: 5, width: 0.3, softness: 0.35, accent: 0.5 } },
  { id: 'moorish', name: 'Moorish Star', tileFrac: 0.35,
    uses: ['density', 'width', 'softness', 'accent', 'detail', 'variation'],
    labels: { width: 'strap', accent: 'starSize', detail: 'doubleLine', variation: 'raisedFields' },
    params: { pattern: 'moorish', density: 3, width: 0.4, softness: 0.5, accent: 1, detail: 0.6, variation: 0 } },
  // ── Luxury materials ──
  { id: 'intrecciato', name: 'Intrecciato', tileFrac: 0.3,
    uses: ['density', 'width', 'softness', 'accent'], labels: { density: 'strips', width: 'stripWidth', softness: 'edgeRound', accent: 'weaveDepth' },
    params: { pattern: 'intrecciato', density: 5, width: 0.85, softness: 0.6, accent: 0.6 } },
  { id: 'matelasse', name: 'Matelassé', tileFrac: 0.3,
    uses: ['density', 'softness', 'accent', 'detail'], labels: { softness: 'puff', accent: 'seamDepth', detail: 'topstitch' },
    params: { pattern: 'matelasse', density: 3, softness: 0.65, accent: 0.7, detail: 0.8 } },
  { id: 'crackle', name: 'Crackle Glaze', tileFrac: 0.35,
    uses: ['density', 'width', 'accent', 'detail'], labels: { density: 'cells', width: 'crackWidth', accent: 'crazing', detail: 'glazeDome' },
    params: { pattern: 'crackle', density: 4, width: 0.3, accent: 0.6, detail: 0.6 } },
  { id: 'brushed', name: 'Brushed Metal', tileFrac: 0.4,
    uses: ['density', 'angle', 'variation'], labels: { density: 'fineness', variation: 'scratches' },
    params: { pattern: 'brushed', density: 20, angle: 0, variation: 0.3 } },
  // ── Architecture / folding ──
  { id: 'coffered', name: 'Coffered', tileFrac: 0.35,
    uses: ['density', 'angle', 'width', 'softness', 'detail', 'accent'],
    labels: { density: 'panels', width: 'panelSize', detail: 'steps', accent: 'rosette' },
    params: { pattern: 'coffered', density: 3, angle: 0, width: 0.85, softness: 0.25, detail: 0.5, accent: 0.4 } },
  { id: 'miura', name: 'Miura Fold', tileFrac: 0.35,
    uses: ['density', 'waveCount', 'softness', 'accent'], labels: { density: 'pleats', waveCount: 'folds', accent: 'foldDepth' },
    params: { pattern: 'miura', density: 8, waveCount: 3, softness: 0, accent: 0.5 } },
  // ── Tribal ──
  { id: 'tribalBlades', name: 'Tribal Blades', tileFrac: 0.5,
    uses: ['density', 'width', 'softness', 'waviness', 'detail', 'asymmetry', 'scatter', 'rotation', 'scaleVar'], ranges: { density: [1, 8] }, labels: { density: 'strokes', width: 'weight', waviness: 'sweep', detail: 'innerLine' },
    params: { pattern: 'tribalBlades', density: 4, width: 0.55, softness: 0.3, waviness: 0.5, detail: 0, asymmetry: 0 } },
  { id: 'tatau', name: 'Polynesian Tatau', tileFrac: 0.45,
    uses: ['density', 'width', 'softness', 'accent'], labels: { density: 'bands', width: 'weight', accent: 'motifDensity' },
    params: { pattern: 'tatau', density: 6, width: 0.4, softness: 0.25, accent: 0.4 } },
  { id: 'koru', name: 'Koru Spirals', tileFrac: 0.35,
    uses: ['density', 'waveCount', 'width', 'softness', 'accent', 'detail'], labels: { density: 'spirals', waveCount: 'coil', width: 'weight', accent: 'bulb', detail: 'outline' },
    params: { pattern: 'koru', density: 4, waveCount: 3, width: 0.45, softness: 0.4, accent: 0.5, detail: 0 } },
  { id: 'tribalFlames', name: 'Tribal Flames', tileFrac: 0.45,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'detail', 'variation', 'asymmetry', 'scatter', 'rotation', 'scaleVar'], ranges: { density: [1, 6] },
    labels: { density: 'motifs', width: 'weight', waviness: 'curl', accent: 'spikes', detail: 'overlapGap', variation: 'motifVariety' },
    params: { pattern: 'tribalFlames', density: 2, width: 0.5, softness: 0.25, waviness: 0.5, accent: 0.5, detail: 0.3, variation: 0, asymmetry: 0 } },
  { id: 'tribalArmband', name: 'Tribal Armband', tileFrac: 0.35,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'detail', 'variation', 'asymmetry', 'scatter', 'rotation', 'scaleVar'], ranges: { density: [1, 6] },
    labels: { density: 'motifs', width: 'weight', waviness: 'curl', accent: 'spikes', detail: 'overlapGap', variation: 'motifVariety' },
    params: { pattern: 'tribalArmband', density: 2, width: 0.5, softness: 0.25, waviness: 0.5, accent: 0.6, detail: 0.3, variation: 0, asymmetry: 0 } },
  { id: 'tribalSwirl', name: 'Tribal Swirl', tileFrac: 0.4,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'detail', 'variation', 'asymmetry', 'scatter', 'rotation', 'scaleVar'], ranges: { density: [1, 6] },
    labels: { density: 'motifs', width: 'weight', waviness: 'curl', accent: 'thorns', detail: 'overlapGap', variation: 'motifVariety' },
    params: { pattern: 'tribalSwirl', density: 2, width: 0.45, softness: 0.25, waviness: 0.4, accent: 0.5, detail: 0.3, variation: 0, asymmetry: 0 } },
  // ── Cyber sigilism ──
  { id: 'sigilCrest', name: 'Sigil Crest', tileFrac: 0.4,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'detail', 'variation', 'asymmetry', 'scatter', 'rotation', 'scaleVar'], ranges: { density: [1, 6] },
    labels: { density: 'motifs', width: 'lineWeight', waviness: 'sweep', accent: 'rings', variation: 'motifVariety' },
    params: { pattern: 'sigilCrest', density: 3, width: 0.4, softness: 0.7, waviness: 0.5, accent: 0.5, detail: 0, variation: 0.5, asymmetry: 0 } },
  { id: 'chromeThorns', name: 'Chrome Thorns', tileFrac: 0.4,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'detail', 'variation', 'asymmetry', 'scatter', 'rotation', 'scaleVar'], ranges: { density: [1, 6] },
    labels: { density: 'motifs', width: 'lineWeight', waviness: 'curl', accent: 'thorns', variation: 'motifVariety' },
    params: { pattern: 'chromeThorns', density: 3, width: 0.45, softness: 0.7, waviness: 0.5, accent: 0.5, detail: 0, variation: 0.6, asymmetry: 0 } },
  { id: 'barbedWire', name: 'Barbed Wire', tileFrac: 0.35,
    uses: ['density', 'waveCount', 'width', 'waviness', 'accent'], ranges: { density: [1, 10] }, labels: { density: 'strands', waveCount: 'twists', width: 'lineWeight', waviness: 'sag', accent: 'barbSize' },
    params: { pattern: 'barbedWire', density: 4, waveCount: 3, width: 0.4, waviness: 0.3, accent: 0.5 } },
  { id: 'neoTribal', name: 'Neo-Tribal Outline', tileFrac: 0.45,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'detail', 'variation', 'asymmetry', 'scatter', 'rotation', 'scaleVar'], ranges: { density: [1, 6] },
    labels: { density: 'motifs', width: 'lineWeight', waviness: 'curl', accent: 'spikes', detail: 'doubleLine', variation: 'motifVariety' },
    params: { pattern: 'neoTribal', density: 2, width: 0.35, softness: 0.3, waviness: 0.6, accent: 0.5, detail: 0.6, variation: 0.5, asymmetry: 0 } },
  { id: 'sigilGlyphs', name: 'Sigil Glyphs', tileFrac: 0.35,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'detail', 'variation', 'asymmetry', 'scatter', 'rotation', 'scaleVar'], ranges: { density: [1, 6] },
    labels: { density: 'motifs', width: 'lineWeight', accent: 'complexity', variation: 'motifVariety' },
    params: { pattern: 'sigilGlyphs', density: 4, width: 0.4, softness: 0.3, waviness: 0, accent: 0.5, detail: 0, variation: 1, asymmetry: 0 } },
  { id: 'chromeDrips', name: 'Chrome Drips', tileFrac: 0.4,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'detail', 'variation', 'asymmetry', 'scatter', 'rotation', 'scaleVar'], ranges: { density: [1, 6] },
    labels: { density: 'motifs', width: 'blobSize', softness: 'dome', accent: 'dripLength', variation: 'motifVariety' },
    params: { pattern: 'chromeDrips', density: 4, width: 0.5, softness: 0.5, waviness: 0, accent: 0.5, detail: 0, variation: 0.8, asymmetry: 0.3 } },
  { id: 'cyberSigil', name: 'Cyber Sigil', tileFrac: 0.5,
    uses: ['density', 'width', 'softness', 'waviness', 'accent', 'asymmetry', 'scatter', 'rotation', 'scaleVar'], ranges: { density: [1, 5] }, labels: { density: 'strokes', width: 'lineWeight', waviness: 'sweep', accent: 'nodes' },
    params: { pattern: 'cyberSigil', density: 3, width: 0.3, softness: 0.25, waviness: 0.4, accent: 0.3, asymmetry: 0 } },
  { id: 'thornVines', name: 'Thorn Vines', tileFrac: 0.4,
    uses: ['density', 'waveCount', 'width', 'softness', 'waviness', 'accent'], ranges: { density: [1, 12] }, labels: { density: 'vines', waveCount: 'thorns', width: 'lineWeight', waviness: 'flow', accent: 'thornLength' },
    params: { pattern: 'thornVines', density: 5, waveCount: 3, width: 0.35, softness: 0.3, waviness: 0.5, accent: 0.5 } },
  // ── Organic growth (tribal / cyber) ──
  { id: 'tribalGrowth', name: 'Tribal Growth', tileFrac: 0.9,
    uses: ['density', 'width', 'softness', 'accent', 'detail', 'length', 'curl', 'flow', 'branching', 'thorns', 'spacing', 'variation', 'asymmetry'], ranges: { density: [1, 30] },
    labels: { density: 'strokes', width: 'weight', accent: 'hook', detail: 'overlapGap', variation: 'chaos' },
    params: { pattern: 'tribalGrowth', density: 18, width: 0.75, softness: 0.25, accent: 0.5, detail: 0.4, length: 0.5, curl: 0.45, flow: 0.4,
              branching: 0.5, thorns: 0.35, spacing: 0.18, variation: 0.6, asymmetry: 0 } },
  { id: 'sigilGrowth', name: 'Sigil Growth', tileFrac: 0.9,
    uses: ['density', 'width', 'softness', 'accent', 'detail', 'length', 'curl', 'flow', 'branching', 'thorns', 'spacing', 'variation', 'asymmetry'], ranges: { density: [1, 30] },
    labels: { density: 'strokes', width: 'lineWeight', accent: 'hook', detail: 'rings', variation: 'chaos' },
    params: { pattern: 'sigilGrowth', density: 12, width: 0.45, softness: 0.7, accent: 0.35, detail: 0.35, length: 0.55, curl: 0.3, flow: 0.35,
              branching: 0.5, thorns: 0.6, spacing: 0.2, variation: 0.6, asymmetry: 0 } },
  { id: 'barbedGrowth', name: 'Barbed Vines', tileFrac: 0.9,
    uses: ['density', 'width', 'softness', 'accent', 'detail', 'length', 'curl', 'flow', 'branching', 'thorns', 'spacing', 'variation', 'asymmetry'], ranges: { density: [1, 30] },
    labels: { density: 'strokes', width: 'lineWeight', accent: 'hook', detail: 'rings', variation: 'chaos' },
    params: { pattern: 'barbedGrowth', density: 16, width: 0.45, softness: 0.7, accent: 0.2, detail: 0, length: 0.7, curl: 0.35, flow: 0.6,
              branching: 0.25, thorns: 0.6, spacing: 0.18, variation: 0.5, asymmetry: 0.5 } },
  // ── Organic ──
  { id: 'drapery', name: 'Drapery', tileFrac: 0.5,
    uses: ['density', 'angle', 'softness', 'waviness', 'variation'],
    params: { pattern: 'drapery', density: 5, angle: 80, softness: 0.3, waviness: 0.2, variation: 0.3 } },
  { id: 'contours', name: 'Topographic', tileFrac: 0.5,
    uses: ['density', 'width', 'softness', 'waviness', 'accent'], labels: { accent: 'terracing' },
    params: { pattern: 'contours', density: 12, width: 0.25, softness: 0.5, waviness: 0.3, accent: 0 } },
];

export const DEFAULT_DESIGN_TYPE = 'flowLines';

export function designTypeById(id) {
  return DESIGN_TYPES.find(d => d.id === id) || null;
}
